### ISSUE TITLE
mktemp: failed to create file via template '...': Permission denied

### ISSUE THREAD

**Issue by Zimmi48** [nix-community/docker-nix#15]
Hi,

Our Nix GitLab CI tests at Coq are using the image `nixorg/nix:latest` and they started failing after the merge of #14. I suppose the faulty commit is cff25a0175d9c8a28593193745248b8b710540bc but I have no idea why.
Our test-suite Makefile calls `mktemp /tmp/coqcheck.XXXXXX` and this fails with a permission denied.

Can you fix this or help me understand what to change on our side?

Thanks!

**Comment by zimbatm** [comment]
Hi,

can you give me a little bit more outputs or point me to the logs? I executed a container and ran `mktemp /tmp/coqcheck.XXXXXX` and it's working fine here.

**Comment by Zimmi48** [comment]
Thanks.
The GitLab CI configuration of the Nix job is here: https://github.com/coq/coq/blob/8b176e3b0e42b34db3165d9e1ce45fff0e581335/.gitlab-ci.yml#L216-L243

It contains this:
```
# Use current worktree as tmpdir to allow exporting artifacts in case of failure
export TMPDIR=$PWD
```

which has strong chances of being related to the failure. Sorry for forgetting about this earlier.

Here is where `mktemp` is called: https://github.com/coq/coq/blob/8b176e3b0e42b34db3165d9e1ce45fff0e581335/test-suite/Makefile#L399

and here is a log of a failed job: https://gitlab.com/coq/coq/-/jobs/89846984

**Comment by zimbatm** [comment]
Okay, thanks for the pointers!

I checked the image sha256 from the gitlab logs and it corresponds to the current `nixorg/nix:latest`.

Running locally:
```
$ docker run -ti --rm nixorg/nix
bash-4.4# TMPDIR=/root mktemp /tmp/foo.XXXXXXX
/tmp/foo.EL0gjod
bash-4.4# ls -la /tmp/
total 8
drwxr-xr-x 1 root root 4096 Aug 16 18:35 .
drwxr-xr-x 1 root root 4096 Aug 16 18:30 ..
-rw------- 1 root root    0 Aug 16 18:34 foo.EL0gjod
```

I noticed that `mktemp` is ignoring the TMPDIR. Looking at the man pages it looks like you would have to use it like `mktemp -p "" coqckeck.XXXXXX` instead. Changing the Makefile to this might fix the issue for you.

I still don't know why the new image broke the builds. It would be helpful if you could run another build with `ls -la /tmp` so I can check the permissions. Thanks!

**Comment by Zimmi48** [comment]
Thanks for your advice!

>I still don't know why the new image broke the builds. It would be helpful if you could run another build with ls -la /tmp so I can check the permissions.

https://gitlab.com/Zimmi48/coq/-/jobs/89899257

```
$ ls -la /tmp
total 16
drwxr-xr-x 2 root root 4096 Apr  6 12:37 .
drwxr-xr-x 1 root root 4096 Aug 16 19:18 ..
```

**Comment by zimbatm** [comment]
Weird, it looks like everything is open as expected. Can you replace it with `mktemp` to see if the problem is only further below?

**Comment by Zimmi48** [comment]
https://gitlab.com/Zimmi48/coq/-/jobs/89900181

`mktemp` seems to succeed before and after the `export TMPDIR=$PWD`

That's really weird indeed.

**Comment by Zimmi48** [comment]
A note that could be of importance: this failing `mktemp` is running during the `installCheck` phase (after install), see https://github.com/coq/coq/blob/8b176e3b0e42b34db3165d9e1ce45fff0e581335/default.nix#L90. I'm going to try replacing this `installCheck` phase with a call to `ls -la /tmp` to see what it gives.

**Comment by Zimmi48** [comment]
`ls -la /tmp` shows the same permissions:
```
drwxr-xr-x 2 root root 4096 Apr  6 12:37 .
drwxr-xr-x 1 root root 4096 Aug 16 19:55 ..
```

but the "user" could be a Nix builder which has less permissions than root, couldn't it?

**Comment by zimbatm** [comment]
Ok, thanks for your patience, I can reproduce the issue now.

`default.nix`:
```nix
let
  nixpkgs = builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz";
  };
  pkgs = import nixpkgs { config = {}; overlays = []; };
in
with pkgs;
stdenv.mkDerivation {
  name = "test";

  builder = writeScript "builder.sh" ''
    export PATH=${coreutils}/bin
    mktemp
    mktemp /tmp/foo.XXXXXXXX
    ls -la /tmp
    mkdir $out
  '';
}
```

It works fine locally but fails when I run `docker run -v $PWD:/src --workdir /src --rm -ti nixorg/nix nix-build`

**Comment by zimbatm** [comment]
side note: build sandboxing is not available inside of docker without the `--privileged` access

**Comment by zimbatm** [comment]
`nixorg/nix:1` (previous)
```
drwxrwxrwt 1 root    root   4096 Aug 16 21:07 .
drwxr-xr-x 1 root    root   4096 Aug 16 21:07 ..
drwxr-xr-x 2 root    root   4096 Aug 16 21:07 nix-build-1-0
drwx------ 2 nixbld1 nixbld 4096 Aug 16 21:07 nix-build-test.drv-0
```

`nixorg/nix:latest`
```
total 16
drwxr-xr-x 1 root    root   4096 Aug 16 21:09 .
drwxr-xr-x 1 root    root   4096 Aug 16 21:09 ..
drwxr-xr-x 2 root    root   4096 Aug 16 21:09 nix-build-1-0
drwx------ 2 nixbld1 nixbld 4096 Aug 16 21:09 nix-build-test.drv-0
```

so the new version is less permissive on /tmp

```
$ docker run -v $PWD:/src --workdir /src --rm -ti nixorg/nix:1 readlink /nix/var/nix/profiles/default/bin/nix
/nix/store/6p2gambjac7xdkd2a7w1dsxdk1q5cq4d-nix-2.0/bin/nix
```

```
$ docker run -v $PWD:/src --workdir /src --rm -ti nixorg/nix readlink /nix/var/nix/profiles/default/bin/nix
/nix/store/6p2gambjac7xdkd2a7w1dsxdk1q5cq4d-nix-2.0/bin/nix
```

They both have the same version of nix

**Comment by zimbatm** [comment]
So for reason the container has been created with the wrong /tmp mode. When running as root it's fine obviously but nix is running as nixbld1 so it fails.

I will push an update to fix this soon.

**Comment by zimbatm** [comment]
it should be fixed once https://hub.docker.com/r/nixorg/nix/builds/bctaeixqexjuwaghgfapagg/ finished building

**Comment by Zimmi48** [comment]
Great, thanks!

**Comment by Zimmi48** [comment]
I confirm that this solved the issue.
